### ISSUE TITLE
FFI::NullPointerError: invalid memory read at address=0x00000000000000

### ISSUE THREAD

**Issue by jerrydeng** [watsonbox/pocketsphinx-ruby#5]
When trying to decode the goforward.raw audio, anytime I run decoder.hypothesis.  I get the following error:
FFI::NullPointerError: invalid memory read at address=0x00000000000000
In pointer.rb with get_string method

**Comment by watsonbox** [comment]
Thanks.  I'd guess this is due to an [interface change](https://github.com/cmusphinx/pocketsphinx/commit/b638fabe6903099e1443592a4b052641c6271d6a) in the Pocketsphinx API.  Unfortunately until some up to date releases are made this is going to happen from time to time.

I'll sort it later this week unless anyone beats me to it!

@nshmyrev Are there likely to be any official stable releases in the near future?

**Comment by nshmyrev** [comment]
Yes, we going to make a stable release soon, few bits left.
